server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: travel-plan-backend
    # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel_plan
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  profiles:
    active: local
  # 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB
  # Redis 配置
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: ${spring.datasource.password}
      timeout: 5000
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
#  ai:
#    vectorstore:
#      pgvector:
#        index-type: HNSW
#        dimensions: 1536
#        distance-type: COSINE_DISTANCE
#        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
# 临时注释
#    mcp:
#      client:
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8127
#        stdio:
#        servers-configuration: classpath:mcp-servers.json
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # ??????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.fawnyr.travelplanbackend.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchApi
search-api:
  api-key: ${search-api.api-key}
